spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    username: root
    password: Th123066
    url: jdbc:mysql://localhost:3306/owl_assistant?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: owl_assistant

server:
  port: 8989
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath:com/end/mapper/*.xml
  type-aliases-package: com.end.domain

